### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by sysfox** [WhaleFell/CameraHack#1]
好家伙，不至于吧，这一个女高一学生还hack摄像头？？？ϵ( 'Θ' )϶
是我太逊了吗？

**Comment by WhaleFell** [comment]
放假无聊整的活）不是你太逊，是我太菜，不信可以看看我代码哦。

**Comment by sysfox** [comment]
> 放假无聊整的活）不是你太逊，是我太菜，不信可以看看我代码哦。

。。。我连Python里的turtle库都不会。。。
我们学校不让我们上整整一个月的信技，就没教python，结果这个学期信技结业考试就考了，我们班几乎全部阵亡

**Comment by cy920820** [comment]
好家伙，现在初、高中生直接开始考 python 了？

**Comment by sysfox** [comment]
> 好家伙，现在初、高中生直接开始考 python 了？

的确，但教的是基础的：像画画这一类，不至于考到爬虫这种级别，而且都是选择题和判断题
