### ISSUE TITLE
我看刑，写的很可铐

### ISSUE THREAD

**Issue by veo** [WhaleFell/CameraHack#2]

**Comment by WhaleFell** [comment]
我写的代码很垃圾。。

**Comment by veo** [comment]
现在不比以前。谨言慎行，方向别找错

**Comment by veo** [comment]
摄像头和短信这种东西还是挺敏感的。有时间可以来先知，freebuf ，安全客 找我们玩

**Comment by sysfox** [comment]
> 摄像头和短信这种东西还是挺敏感的。有时间可以来先知，freebuf ，安全客 找我们玩

Github上这东西应该不敏感吧？

**Comment by yuangu** [comment]
写的确实不错，我都怀疑是不是中学生了
