### ISSUE TITLE
求公布使用方法 步骤和使用教程

### ISSUE THREAD

**Issue by binghe123** [WhaleFell/CameraHack#5]

**Comment by yz1639** [comment]
看了源码，没研究出来怎么用的

**Comment by w311ang** [comment]
似乎是在sst.txt中放入要扫描的大华/海康威视摄像头的ip，然后再运行main.py

https://chat.openai.com/share/c3ec7baf-2bce-4756-b615-4aa8110a81bd

**Comment by WhaleFell** [comment]
Reading Code! Using hands!
